import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ClientProviders from "./client-providers";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/navbar/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Cosmo web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
          <ClientProviders>
            <div className="relative flex min-h-dvh flex-col">
              <Navbar />
              <div className="flex min-w-full flex-col text-foreground">
                {children}
              </div>
            </div>
          </ClientProviders>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
